> Ciria, A., Rojas-Galeano, S., Marmolejo-Ramos, F., Tejada, J., & Lara, B. (2026). *Cross-Linguistic Evaluation of Sensorimotor Norms Generated by Large Language Models: Beyond Mean-Level Alignment*.   

The present application extends and adapts both, the interactive web application to visualize the sensorimotor profile of individual concepts from Lynott et al. (2020), and the Sensorimotor Distance Calculator from Wingfield & Connell (2023), to enable the analysis and comparison of synthetic sensorimotor norms generated by Large Language Models (LLMs). Specifically, the app allows users to compare sensorimotor norms across multiple languages, English (Lynott et al., 2020), Italian (Repetto et al., 2022), Chinese (Zhong et al., 2022), Croatian (Popović Stijačić et al., 2023), and Mexican Spanish (Villaseñor, 2025), and across Large Language Models, including **GPT-4.1 Nano** and **DeepSeek V3.2**.

The underlying sensorimotor space is defined over 11 dimensions, comprising six perceptual modalities (auditory, gustatory, haptic, interoceptive, olfactory, and visual) and five action effectors (foot/leg, hand/arm, head, mouth, and torso), following the structure of the Lancaster Sensorimotor Norms (Lynott et al., 2020). In this study, synthetic sensorimotor norms were generated across languages using **GPT-4** and **DeepSeek V3** via participant-level simulations that approximate the original distributions of age and gender, with instructions and stimuli presented in the corresponding native language. The resulting norms include mean ratings, standard deviations, and derived measures such as Minkowski-3 distance, Exclusivity, and Dominant modality/effector indices for perceptual, action, and combined sensorimotor dimensions.

---

### Core Analytical Features

This application provides a comprehensive suite of tools for investigating how conceptual representations vary across linguistic, cultural, and model-based contexts:

*   **Full Datasets:** Browse, search, and download the complete sensorimotor norms for all 15 available sources (English, Chinese, Italian, Croatian, and Mexican Spanish * Human, GPT, and DeepSeek).
*   **Sensorimotor profiles:** Compare the "sensorimotor profile" of individual concepts across two datasets using the classic Lancaster-style radial visualization (polar plots). This feature includes an **overlay mode** to see precisely how a specific language or model dataset profile differs from other dataset profile.
*   **Calculate distances:** Compute semantic similarity using multiple metrics (Cosine, Euclidean, Mahalanobis, etc.) for **one-to-one**, **one-to-many**, or **many-to-many (matrix)** word lists. It supports cross-dataset calculations (e.g., comparing a concept's position in the English Human space vs. the English LLM space).
*   **Nearest neighbours:** Explore the local semantic neighborhood of any concept in any specific language or model dataset.
*   **Visualise concepts:** Use Multidimensional Scaling to observe how groups of concepts shift across two different datasets, with connecting lines highlighting the displacement between semantic spaces.
*   **Sensorimotor space:** Interact with the global structure of each dataset in 3D. 

> **Note:** For a detailed mathematical and methodological explanation of these metrics and tools, please visit the <a href="#" onclick="Shiny.setInputValue('main_nav', 'tab_info');">Information</a> page.

---

### How to Use

Use the navigation bar at the top to select different modes of analysis. Most tools allow you to choose a **Source Dataset (D1)** and a **Comparison Dataset (D2)**. 

- **D1 → D1 / D2 → D2:** Internal conceptual distances within a single source.
- **D1 → D2:** Cross-linguistic or cross-source evaluation (e.g., English Human vs. Italian Human).

If you use this tool in your research, please cite the original work by Lynott et al. (2020), Wingfield & Connell (2023) and the present study by Ciria et al. (2026).

---

### References

**Lancaster Sensorimotor Norms:**  
Lynott, D., Connell, L., Brysbaert, M., Brand, J., & Carney, J. ([2020](https://doi.org/10.3758/s13428-019-01316-z)) *The Lancaster Sensorimotor Norms: Multidimensional measures of perceptual and action strength for 40,000 English words*. *Behavior Research Methods, 52(3),* 1271-1291.

**Sensorimotor Distance Calculator:**  
Wingfield, C. & Connell, L. ([2023](https://doi.org/10.3758/s13428-022-01965-7)) *Sensorimotor distance: A grounded measure of semantic similarity for 800 million concept pairs*. *Behavior Research Methods, 55(7),* 3416-3432.

**Human & Synthetic Sensorimotor Norms Explorer:**  
Ciria, A., Rojas-Galeano, S., Marmolejo-Ramos, F., Tejada, J., & Lara, B. (2026). *Cross-Linguistic Evaluation of Sensorimotor Norms Generated by Large Language Models: Beyond Mean-Level Alignment*.   

**Sensorimotor norms in other languages:**  
Popović Stijačić, M., Filipović Đurđević, D., Sekulić Sović, M., & Erdeljac, V. (2023). *Sensory-motor norms for 372 Croatian words*. Book of Abstracts, *10th Novi Sad Workshop on Psycholinguistic, Neurolinguistic, and Clinical Linguistic Research* (pp. 24–26).

Repetto, C., Rodella, C., Conca, F., Santi, G. C., & Catricalà, E. (2022). *The Italian sensorimotor norms: Perception and action strength measures for 959 words*. *Behavior Research Methods*, 1-13.

Villaseñor, S. (2025). *Análisis representacional de conceptos abstractos y concretos en su uso contextual*. [Tesis de Licenciatura]. Ciudad de México, México. (Tesis dirigida por Alejandra Ciria).

Zhong, Y., Wan, M., Ahrens, K., & Huang, C.-R. (2022). *Sensorimotor norms for Chinese nouns and their relationship with orthographic and semantic variables*. *Language, Cognition and Neuroscience, 37(8)*, 1000–1022.

---

### Code

The codebase is available on GitHub:  
[https://github.com/XXXX](https://github.com/XXXX)

---

### Contact

**Alejandra Ciria**  
alejandra.ciria@unam.mx  
Instituto de Investigaciones en Matemáticas Aplicadas y en Sistemas (IIMAS),
Universidad Nacional Autónoma de México (UNAM)

### Acknowledgements

This work was supported by PAPIIT (Programa de Apoyo a Proyectos de Investigación e Innovación Tecnológica), UNAM, under project IN304825.